In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame({'Text. No.':['D1','D2','D3','D4'],'Text':['people watch movie','movie watch movie','people write comment','movie write comment']})

In [3]:
df

  Text. No.                  Text
0        D1    people watch movie
1        D2     movie watch movie
2        D3  people write comment
3        D4   movie write comment

In [4]:
from sklearn.preprocessing import MultiLabelBinarizer



df['Text Tokenized'] = df['Text'].apply(lambda x: x.split())

# Initialize the MultiLabelBinarizer for one-hot encoding
mlb = MultiLabelBinarizer()

# Perform one-hot encoding on the tokenized words
one_hot_encoded = mlb.fit_transform(df['Text Tokenized'])

# Create a new DataFrame with the one-hot encoded columns
one_hot_df = pd.DataFrame(one_hot_encoded, columns=mlb.classes_)

# Combine the original dataframe with the one-hot encoded columns
df_final = pd.concat([df, one_hot_df], axis=1)

# Display the result
df_final

,Text. No.,Text,Text Tokenized,comment,movie,people,watch,write
0,D1,people watch movie,"[people, watch, movie]",0,1,1,1,0
1,D2,movie watch movie,"[movie, watch, movie]",0,1,0,1,0
2,D3,people write comment,"[people, write, comment]",1,0,1,0,1
3,D4,movie write comment,"[movie, write, comment]",1,1,0,0,1

In [4]:
np.array(df['Text'])

array(['people watch movie', 'movie watch movie', 'people write comment',
       'movie write comment'], dtype=object)

In [5]:
L=[]
s=''
for i in df['Text']:
    s=s+i+' '
    a=len(i.split())
    for j in range(a):
        L.append([0,0,0,0,0])
print(L)
    
li=s.split()
vocabulory=set(li)
print(vocabulory)

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]
{'write', 'watch', 'comment', 'movie', 'people'}

In [6]:
print(li)

['people', 'watch', 'movie', 'movie', 'watch', 'movie', 'people', 'write', 'comment', 'movie', 'write', 'comment']

In [7]:
for i in df['Text']:
    print(i.split())

['people', 'watch', 'movie']
['movie', 'watch', 'movie']
['people', 'write', 'comment']
['movie', 'write', 'comment']

In [8]:
c=0
for i in vocabulory:
    for j in df['Text']:
        if i in j:
            b=j.split().index(i) #0
    L[c].insert(b,1)
            
    c=c+1
print(L)

[[0, 1, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0], [1, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]

In [9]:
np.array(L)

C:\Users\verma\AppData\Local\Temp\ipykernel_1248\1461958951.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array(L)

array([list([0, 1, 0, 0, 0, 0]), list([0, 1, 0, 0, 0, 0]),
       list([0, 0, 1, 0, 0, 0]), list([1, 0, 0, 0, 0, 0]),
       list([1, 0, 0, 0, 0, 0]), list([0, 0, 0, 0, 0]),
       list([0, 0, 0, 0, 0]), list([0, 0, 0, 0, 0]),
       list([0, 0, 0, 0, 0]), list([0, 0, 0, 0, 0]),
       list([0, 0, 0, 0, 0]), list([0, 0, 0, 0, 0])], dtype=object)

# Bag Of Words

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
cv=CountVectorizer()
bow=cv.fit_transform(df['Text'])

In [7]:
# vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'movie': 1, 'write': 4, 'comment': 0}

In [8]:
print(bow[0].toarray()) # Document 1
print(bow[1].toarray()) # Document 2
print(bow[2].toarray()) # Document 3
print(bow[3].toarray()) # Documnet 4

[[0 1 1 1 0]]
[[0 2 0 1 0]]
[[1 0 1 0 1]]
[[1 1 0 0 1]]

In [9]:
# for new sentence
cv.transform(['movie watch and write comment of movie']).toarray() # prediction

array([[1, 2, 0, 1, 1]], dtype=int64)

In [12]:
# Binary Bag of Words
cv=CountVectorizer(    binary=True,
)
bow=cv.fit_transform(df['Text'])

In [13]:
print(bow[0].toarray()) # Document 1
print(bow[1].toarray()) # Document 2
print(bow[2].toarray()) # Document 3
print(bow[3].toarray()) # Documnet 4

[[0 1 1 1 0]]
[[0 1 0 1 0]]
[[1 0 1 0 1]]
[[1 1 0 0 1]]

# N-grams

In [32]:
# Bi-grams
cv=CountVectorizer(ngram_range=(2,2))
bow=cv.fit_transform(df['Text'])

In [33]:
# vocab
print(cv.vocabulary_)

{'people watch': 2, 'watch movie': 4, 'movie watch': 0, 'people write': 3, 'write comment': 5, 'movie write': 1}

In [34]:
# Tri-grams
cv=CountVectorizer(ngram_range=(3,3))
bow=cv.fit_transform(df['Text'])
print(cv.vocabulary_)

{'people watch movie': 2, 'movie watch movie': 0, 'people write comment': 3, 'movie write comment': 1}

# Tf-Idf

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [28]:
tfidf=TfidfVectorizer()
tfidf.fit_transform(df['Text']).toarray()

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [29]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]
['comment' 'movie' 'people' 'watch' 'write']